#!/usr/bin/env bash
#
# Runs the Python dev script.
#
set -o nounset -o errexit -o pipefail

if ! command -v uv &> /dev/null; then
    echo "uv not installed"
    exit 1
fi

exec uv run --dev python -m scripts.dev "$@"
